# Generated by Django 4.1.7 on 2023-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('ano_nasc', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
